# Generated by Django 3.2 on 2021-04-06 21:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('secondName', models.CharField(max_length=20)),
                ('firstName', models.CharField(max_length=20)),
                ('thirdName', models.CharField(max_length=20)),
                ('phone', models.CharField(max_length=20)),
                ('email', models.CharField(max_length=20)),
                ('birthDate', models.DateField()),
            ],
            options={
                'db_table': 'Client',
            },
        ),
        migrations.CreateModel(
            name='Doc',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('passportIssue', models.DateField(blank=True, null=True)),
            ],
            options={
                'db_table': 'Doc',
            },
        ),
        migrations.CreateModel(
            name='InsuredEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=100)),
                ('hint', models.CharField(max_length=100)),
                ('impactPrice', models.FloatField()),
            ],
            options={
                'db_table': 'InsuredEvent',
            },
        ),
        migrations.CreateModel(
            name='ForeignPassport',
            fields=[
                ('seriesAndNumber', models.CharField(blank=True, max_length=20, null=True)),
                ('doc', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='core.doc')),
            ],
            options={
                'db_table': 'ForeignPassport',
            },
        ),
        migrations.CreateModel(
            name='IDCard',
            fields=[
                ('issuedBy', models.CharField(blank=True, max_length=20, null=True)),
                ('number', models.CharField(blank=True, max_length=20, null=True)),
                ('notation', models.CharField(blank=True, max_length=20, null=True)),
                ('doc', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='core.doc')),
            ],
            options={
                'db_table': 'IDCard',
            },
        ),
        migrations.CreateModel(
            name='UkrainePassport',
            fields=[
                ('seriesAndNumber', models.CharField(max_length=20)),
                ('issuedBy', models.CharField(max_length=20)),
                ('doc', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='core.doc')),
            ],
            options={
                'db_table': 'UkrainePassport',
            },
        ),
        migrations.CreateModel(
            name='Police',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('geoJson', models.TextField()),
                ('cadastralNumber', models.CharField(max_length=20)),
                ('price', models.FloatField()),
                ('term', models.IntegerField()),
                ('coating', models.FloatField()),
                ('startDate', models.DateField()),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.client')),
                ('ensuredEvents', models.ManyToManyField(to='core.InsuredEvent')),
            ],
            options={
                'db_table': 'Police',
            },
        ),
        migrations.AddField(
            model_name='client',
            name='doc',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.doc'),
        ),
    ]
