# Generated by Django 3.1.7 on 2021-03-10 22:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstName', models.CharField(max_length=50, verbose_name="Ім'я")),
                ('secondName', models.CharField(max_length=50, verbose_name='Прізвище')),
                ('passport', models.ImageField(upload_to='passports/', verbose_name='Паспортні дані')),
            ],
            options={
                'verbose_name': ('Клієнт',),
                'verbose_name_plural': 'Клієнти',
            },
        ),
        migrations.CreateModel(
            name='Field',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name="Ім'я поля")),
                ('lt', models.FloatField(verbose_name='Широта')),
                ('lg', models.FloatField(verbose_name='Довгота')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.client', verbose_name='Клієнт')),
            ],
            options={
                'verbose_name': ('Поле',),
                'verbose_name_plural': 'Поля',
            },
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
